export const RouteNames = {
  DEFAULT: '/',
  HOME: '/home',
  ADMIN: '/admin',
  ABOUT: '/about',
  ACADEMICS: '/academics',
  ACTIVITIES: '/activities',
  CONTACT: '/contact',
  GALLERY: '/gallery',
  PRINCIPAL_MESSAGE: '/principal-message',
  RULES_REGULATIONS: '/rules-regulations',
  FEE_STRUCTURE: '/fee-structure',
  ADMISSION_ELIGIBILITY: '/admission-eligibility',
  FACULTY: '/faculty',
  FUTURE_PROGRAMMES: '/future-programmes',
  STUDENT_UNIFORM: '/student-uniform',
  RESULT: '/result',
  ACADEMIC_PERFORMANCE: '/academic-performance',
  NOTICE_BOARD: '/notice-board',
  ALERTS: '/alerts',
  // Quick Access Routes
  IQAC: '/iqac',
  COMMITTEE_CELLS: '/committee-cells',
  SSR: '/ssr',
  ACADEMIC_CALENDAR: '/academic-calendar',
  AICTE: '/aicte',
  MISC_DOCUMENTS: '/misc-documents',
  HELP_DESK: '/help-desk',
  AQAR: '/aqar',
} as const;

export type RouteNamesType = (typeof RouteNames)[keyof typeof RouteNames];
